version: "3.4"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
    - "node.name=es-node"
    - "discovery.type=single-node"
    - "cluster.name=app-search-docker-cluster"
    - "bootstrap.memory_lock=true"
    - "ELASTIC_PASSWORD=elasticpassword"
    - "xpack.security.enabled=true"
    - "xpack.license.self_generated.type=trial"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  app-search:
    image: docker.elastic.co/app-search/app-search:7.6.2
    environment:
    - "elasticsearch.host=http://elasticsearch:9200"
    - "elasticsearch.password=elasticpassword"
    - "app_search.listen_host=0.0.0.0"
    - "APP_SEARCH_DEFAULT_PASSWORD=password"
    - "allow_es_settings_modification=true"
    - "secret_session_key=833015eb940d5299db0957aea5bbe451921fdb31e05d61600d0cdb65caf2c632a1fbc8623c7d333e59596dd7316758e6629a2290c06c621e33e025d6f474a622"
    ports:
    - 3002:3002
  frontend:
    build: 
      context: '.'
      target: frontend
    environment: 
    - "AS_BASE_URL=http://host.docker.internal:3002/"
    - "AS_USERNAME=app_search"
    - "AS_PASSWORD=password"
    ports:
    - 5000:5000
  dataimport:
    build: 
      context: '.'
      target: dataimport
    environment: 
    - "AS_BASE_URL=http://host.docker.internal:3002/"
    - "AS_USERNAME=app_search"
    - "AS_PASSWORD=password"
volumes:
  esdata:
