version: "3.4"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
    - "node.name=es-node"
    - "discovery.type=single-node"
    - "cluster.name=app-search-docker-cluster"
    - "bootstrap.memory_lock=true"
    - "ELASTIC_PASSWORD=elasticpassword"
    - "xpack.security.enabled=true"
    - "xpack.license.self_generated.type=trial"
    ports:
    - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  enterprise_search:
    image: docker.elastic.co/enterprise-search/enterprise-search:7.8.0
    environment:
    - "elasticsearch.host=http://elasticsearch:9200"
    - "elasticsearch.password=elasticpassword"
    - "ENT_SEARCH_DEFAULT_PASSWORD=password"
    - "allow_es_settings_modification=true"
    - "secret_management.encryption_keys=[changeme]"
    ports:
    - 3002:3002
  frontend:
    build:
      context: '.'
      target: frontend
    environment:
    - "AS_BASE_URL=http://host.docker.internal:3002/"
    - "AS_USERNAME=enterprise_search"
    - "AS_PASSWORD=password"
    ports:
    - 5000:5000
  dataimport:
    build:
      context: '.'
      target: dataimport
    environment:
    - "AS_BASE_URL=http://host.docker.internal:3002/"
    - "AS_USERNAME=enterprise_search"
    - "AS_PASSWORD=password"
volumes:
  esdata:
